export const LOGIN_SUCCESS 		= 'LOGIN_SUCCESS';
export const LOGIN_ERROR   		= 'LOGIN_ERROR';
export const LOGOUT_SUCCESS   	= 'LOGOUT_SUCCESS';
export const FETCH_PACKAGES_SUCCESS = "FETCH_PACKAGES_SUCCESS";
export const RECEIVE_DATAPACKAGE = 'RECEIVE_DATAPACKAGE';
export const RECEIVE_RESOURCE = 'RECEIVE_RESOURCE';
